source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PodDemoThird_Example', :exclusive => true do
  pod "PodDemoThird", :path => "../"
end

target 'PodDemoThird_Tests', :exclusive => true do
  pod "PodDemoThird", :path => "../"

  pod 'FBSnapshotTestCase'
end
